# Generated by Django 5.2.1 on 2025-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='d_o_p',
            field=models.DateField(default='null', verbose_name='Date Of Purchase (YYYY-MM-DD)'),
        ),
    ]
