# Generated by Django 5.2.1 on 2025-05-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_alter_inventory_d_o_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Receipt'),
        ),
    ]
